rules:
  # Ignore whitelist - we are using it to ignore pydantic in pyproject.toml
  - name: whitelist
ignore_files:
  # Ignore all files under lib dir since they are not managed by the charm.
  - lib/
