name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.1/stable
      provider: lxd
      self-hosted-runner: true
      self-hosted-runner-label: "large"
